FROM oven/bun:1.1.0 as builder
WORKDIR /app

COPY bun.lock package.json ./ 
COPY packages ./packages
RUN bun install
RUN bun run --cwd packages/fe build

FROM nginx:alpine
COPY --from=builder /app/packages/fe/dist /usr/share/nginx/html
COPY packages/fe/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]